### ISSUE TITLE
Need tutorial

### ISSUE THREAD

**Issue by VasiliyRusin** [Inlife/squirrel-orm#1]
Please add simple tutorial how to use it with sqlite for example.

**Comment by inlife** [comment]
Hello,

Here is a simple example with specific SQLite implementation:
https://github.com/inlife/squirrel-orm#mafia-2-online-sqlite-example

It might vary from implementation to implementation, but the general idea should stay the same:

1. include the file (via dofile for example)
2. call `ORM.Driver.setProxy`, providing a function that will be used as a handler for every prepared SQL query, where you will need to call an actual method from your native SQLite library
3. and finally call a configuration method, to finish the setup
```
ORM.Driver.configure({
    provider = "sqlite"
});
```

That should be enough to start working with it

**Comment by VasiliyRusin** [comment]
So this library does not provide any connections between **squirrel** and **sqlite**, does it? Could you recommend any SQLite library for squirrel?

**Comment by inlife** [comment]
Yep, it does not. Same goes for mysql.

The reason is that there are no native built-in bindings for mysql/sqlite libraries in the default squirrel lang implementation. You will need to look for native bindings (most likely in the form of a dll or statically compiled c(++) version of the lang and those modules). Unfortunately, I can't say that I know which lib to recommend for you.
